[build]
  # Branche à déployer
  base = "./"      # ou laissez vide si votre projet est à la racine
  publish = "dist" # Vite utilise 'dist' comme répertoire de build par défaut
  command = "npm run build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF *.config.*"

  # Environnement de production
[build.environment]
  NODE_VERSION = "18"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

# Configuration des redirections et des en-têtes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff" 