[build]
  # Branche à déployer
  publish = "/"
  command = "npm run build"
  functions = "/"

  # Environnement de production
[build.environment]
  NODE_VERSION = "18"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

# Configuration des redirections et des en-têtes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff" 